restart service job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -38,6 +38,23 @@ variables:
   K8S_SECRET_PLATFORM_COMMON: "$PLATFORM_COMMON"
   K8S_SECRET_COMMIT_SHA: "$CI_COMMIT_SHA"
 
+  # These 2 vars are for the form for restarting the service
+  RESTART_SERVICE:
+    value: "false"
+    options:
+      - "false"
+      - "true"
+    description: "Run the restart service script"
+  RESTART_SERVICE_ENV:
+    value: "dev"
+    description: "Environment to restart service in"
+    options:
+      - "dev"
+      - "stage-a"
+      - "stage-b"
+      - "prod-a1"
+      - "prod-a2"
+
 
   DOCKER_DRIVER: overlay2
   DEPLOY_TYPE: "kubernetes" # "kubernetes","beanstalk","both"
@@ -57,6 +74,7 @@ stages:
   - production-2
   - performance
   - cleanup
+  - jobs
 
 build_app:
   stage: app_build
@@ -79,6 +97,8 @@ build_app:
       dotenv: .env
   rules:
     - if: $CI_COMMIT_TAG
+      when: never
+    - if: '$RESTART_SERVICE == "true"'
       when: never
     - when: always
 
@@ -105,10 +125,12 @@ sonarqube-check:
       - "dotnet build"
       - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
   allow_failure: true
-  only:
-    - merge_requests
-    - main
-    - master
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: '$RESTART_SERVICE == "true"'
+      when: never
+    - when: always
 
 build_image:
   stage: build
@@ -123,12 +145,50 @@ build_image:
   rules:
     - if: '$BUILD_DISABLED'
       when: never
+    - if: '$RESTART_SERVICE == "true"'
+      when: never
     - if: $CI_COMMIT_TAG
       when: never
     - when: on_success
   needs:
     - job: build_app
       artifacts: true
+
+restart_service:
+  stage: jobs
+  allow_failure: false
+  image:
+    name: bitnami/kubectl
+  script:
+    - |
+      if [ $RESTART_SERVICE_ENV == "dev" ]; then
+        export RUMBLE_NAMESPACE=player-service-v2-23-dev
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [ $RESTART_SERVICE_ENV == "stage-a" ]; then
+        export RUMBLE_NAMESPACE=player-service-v2-23-stage-a
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [ $RESTART_SERVICE_ENV == "stage-b" ]; then
+        export RUMBLE_NAMESPACE=player-service-v2-23-stage-b
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [ $RESTART_SERVICE_ENV == "prod-a1" ]; then
+        export RUMBLE_NAMESPACE=player-service-v2
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:prod-a1-platform-services
+      elif [ $RESTART_SERVICE_ENV == "prod-a2" ]; then
+        export RUMBLE_NAMESPACE=player-service-v2
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:prod-a2-platform-services
+      else
+        echo "Somehow an invalid environment was selected"
+        exit 666
+      fi
+      echo "Using $RUMBLE_CONTEXT to delete all pods from $RUMBLE_NAMESPACE"
+    - |
+      if [ ! -z "$RUMBLE_NAMESPACE" ]; then
+        kubectl config use-context $RUMBLE_CONTEXT
+        kubectl get pods -o yaml -n $RUMBLE_NAMESPACE | kubectl delete -f -
+      fi
+  rules:
+    - if: '$RESTART_SERVICE == "true"'
+      when: always
 
 include: 
   - '/.gitlab/deploy-k8s.yaml'
